name: Update Maven Index

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-maven-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Need write permission to push changes
    steps:
      - name: Checkout tunnel-java-db
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          repository: khulnasoft-lab/tunnel-java-db
          ref: 553f397a88c12c163573b0d1c9c887aed8a40380
          path: tunnel-java-db

      - name: Checkout maven-index repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          path: maven-index

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b  # v5.4.0
        with:
          go-version-file: tunnel-java-db/go.mod

      - name: Build tunnel-java-db
        run: |
          cd tunnel-java-db
          make build

      # Crawl GCS first as it's more stable than Maven Central.
      - name: Run crawler with GCS source
        run: |
          cd tunnel-java-db
          ./tunnel-java-db crawl --index-dir ${GITHUB_WORKSPACE}/maven-index --shards 8192 --source gcs

      - name: Sort TSV files after GCS update
        run: |
          cd maven-index
          find . -name "*.tsv" -type f | while read file; do
            echo "Sorting $file"
            # Sort by groupId, artifactId, version (columns 1, 2, 3)
            # Using standard string sort for all columns
            sort -t $'\t' -k1,1 -k2,2 -k3,3 -o "$file" "$file"
          done

      - name: Commit GCS changes
        run: |
          cd maven-index
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet || (git commit -m "Update maven index from GCS" && git push) 

      - name: Run crawler with Maven Central source
        run: |
          cd tunnel-java-db
          ./tunnel-java-db crawl --index-dir ${GITHUB_WORKSPACE}/maven-index --shards 8192 --source central

      - name: Sort TSV files after Maven Central update
        run: |
          cd maven-index
          find . -name "*.tsv" -type f | while read file; do
            echo "Sorting $file"
            # Sort by groupId, artifactId, version (columns 1, 2, 3)
            # Using standard string sort for all columns
            sort -t $'\t' -k1,1 -k2,2 -k3,3 -o "$file" "$file"
          done

      - name: Commit Maven Central changes
        run: |
          cd maven-index
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet || (git commit -m "Update maven index from Maven Central" && git push) 
